---
name: 🐛 Bug Report
description: "Report a bug for Umbraco Commerce or its related providers/integrations."
labels: ["bug"]
body:
- type: dropdown
  id: component
  attributes:
    label: "Which component is this issue related to?"
    description: "Select the area where you've encountered the issue"
    options:
      - Umbraco Commerce (Core)
      - Payment Provider
      - Shipping Provider
      - Sales Tax Provider
      - Deploy
      - Checkout
      - Cart
      - Demo Store
      - Other / Not sure
  validations:
    required: true
- type: input
  id: "version"
  attributes:
    label: "Which Umbraco Commerce version are you using? (Please write the *exact* version, example: 10.1.0)"
    description: "Go to the Packages > Installed section in the backoffice to find the version you are using"
  validations:
    required: true
- type: textarea
  id: "summary"
  attributes:
    label: "Bug summary"
    description: "Write a short summary of the bug."
    placeholder: "Try to pinpoint it as much as possible."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Specifics"
    id: "specifics"
    description: "Include logs, screenshots, error messages, etc."
- type: textarea
  attributes:
    label: "Steps to reproduce"
    id: "reproduction"
    description: "How can we reproduce the problem on a clean Umbraco install?"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Expected result / actual result"
    id: "result"
    description: "What did you expect, and what actually happened?"
- type: textarea
  attributes:
    label: "Dependencies"
    id: "dependencies"
    description: "List any related add-ons, providers, or integrations and their versions."
